### ISSUE TITLE
What is the domain for your site?

### ISSUE THREAD

**Issue by abe-101** [toastytortilla/homepage#1]

**Comment by toastytortilla** [comment]
So I tried to get this site up and running on a domain a few months back, but I was unsuccessful and decided to focus my time and energy on my final project. I decided that I would come back around to it later once I knew more... still haven't done it haha

**Comment by abe-101** [comment]
Have you tried following the staffs step by step [guide](https://cs50.readthedocs.io/heroku/)?

**Comment by toastytortilla** [comment]
I didn't know about this back then, but I'm gonna do it now. Thanks for the hookup!

**Comment by toastytortilla** [comment]
So I'm trying to get it up and running on Heroku. It seems like everything is working okay, the build is succeeding, but I keep getting this error:

`2022-01-14T17:18:19.000000+00:00 app[api]: Build succeeded`
`2022-01-14T17:18:21.048643+00:00 heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/favicon.ico" host=ddicocco.herokuapp.com request_id=5896e983-a850-47d7-8f2e-2f2829688932 fwd="70.108.24.76" dyno= connect= service= status=503 bytes= protocol=https`

Have you run into this before? I can't seem to figure out what it means. Shouldn't Heroku be handling the spin up for the web processes? Do I need to include something special in my Procfile or requirements.txt to tell it to handle this?

**Comment by abe-101** [comment]
It seems like its working now
